'use strict';

let calculate = document.getElementById('start');
let plus1 = document.getElementsByTagName('button')[0];
let plus2 = document.getElementsByTagName('button')[1];
let checkbox = document.querySelector('#deposit-check');
let incomeItems = document.querySelectorAll('.additional_income-item');
let budgetMonth = document.getElementsByClassName('budget_month-value');
let budgetDay = document.getElementsByClassName('budget_day-value');
let expensesMonth = document.getElementsByClassName('expenses_month-value');
let additionalIncome = document.getElementsByClassName('additional_income-value');
let additionalExpenses = document.getElementsByClassName('additional_expenses-value');
let incomePeriod = document.getElementsByClassName('income_period-value');
let target = document.getElementsByClassName('target_month-value');
let salaryAmount = document.querySelector('input.salary-amount');
let incomeTitle = document.querySelector('input.income-title');
let incomeAmount = document.querySelector('input.income-amount');
let additionalIncomeItem = document.querySelectorAll('input.additional_income-item')[0];
let additionalIncomeItem1 = document.querySelectorAll('input.additional_income-item')[1];
let expensesTitle = document.querySelector('input.expenses-title');
let expensesAmount = document.querySelector('input.expenses-amount');
let additionalExpensesItem = document.querySelector('input.additional_expenses-item');
let depositCheck = document.querySelector('input.deposit-check');
let depositAmount = document.querySelector('input.deposit-amount');
let depositPercent = document.querySelector('input.deposit-percent');
let targetAmount = document.querySelector('input.target-amount');
let periodSelect = document.querySelector('input.period-select');

console.log(calculate);
console.log(plus1);
console.log(plus2);
console.log(checkbox);
console.log(incomeItems);
console.log(budgetMonth);
console.log(budgetDay);
console.log(expensesMonth);
console.log(additionalIncome);
console.log(additionalExpenses);
console.log(incomePeriod);
console.log(target);
console.log(salaryAmount, incomeTitle,incomeAmount,additionalIncomeItem,additionalIncomeItem1,expensesTitle,expensesAmount,additionalExpensesItem,depositCheck,depositAmount,depositPercent,targetAmount,periodSelect);
