'use strict';

let calculate = document.getElementById('start');
let plus1 = document.getElementsByTagName('button')[0];
let plus2 = document.getElementsByTagName('button')[1];
let checkbox = document.querySelector('#deposit-check');
let incomeItems = document.querySelectorAll('.additional_income-item');
let budgetMonth = document.getElementsByClassName('budget_month-value');
let budgetDay = document.getElementsByClassName('budget_day-value');
let expensesMonth = document.getElementsByClassName('expenses_month-value');
let additionalIncome = document.getElementsByClassName('additional_income-value');
let additionalExpenses = document.getElementsByClassName('additional_expenses-value');
let incomePeriod = document.getElementsByClassName('income_period-value');
let target = document.getElementsByClassName('target_month-value');
let input = document.querySelector('input.salary-amount');
let input1 = document.querySelector('input.income-title');
let input2 = document.querySelector('input.income-amount');
let input3 = document.querySelector('input.additional_income-item');
let input4 = document.querySelector('input.additional_income-item');
let input5 = document.querySelector('input.expenses-title');
let input6 = document.querySelector('input.expenses-amount');
let input7 = document.querySelector('input.additional_expenses-item');
let input8 = document.querySelector('input.deposit-check');
let input9 = document.querySelector('input.deposit-amount');
let input10 = document.querySelector('input.deposit-percent');
let input11 = document.querySelector('input.target-amount');
let input12 = document.querySelector('input.period-select');

console.log(calculate);
console.log(plus1);
console.log(plus2);
console.log(checkbox);
console.log(incomeItems);
console.log(budgetMonth);
console.log(budgetDay);
console.log(expensesMonth);
console.log(additionalIncome);
console.log(additionalExpenses);
console.log(incomePeriod);
console.log(target);
console.log(input, input1,input2,input3,input4,input5,input6,input7,input8,input9,input10,input11,input12);
